"use server";

import { createClient } from "@supabase/supabase-js";
import { whichUser } from "@/app/utils/auth";
import type { Business, AccessKey } from "@/types/users.types";
import { TRIAL_PERIOD_DAYS } from "../utils/constants";


// Define a safe response envelope
export type FetchBusinessesResponse =
    | { success: true; data: Business[] }
    | { success: false; errorType: "UNAUTHORIZED" | "DATABASE_ERROR"; message: string };

export async function fetchAuthenticatedBusinesses(): Promise<FetchBusinessesResponse> {
    const supabase = createClient(
        process.env.SUPABASE_URL!,
        process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    const currentUser = await whichUser.info;
    if (!currentUser) {
        return {
            success: false,
            errorType: "UNAUTHORIZED",
            message: "Your session has expired or you are not logged in."
        };
    }

    const userId = currentUser.id;

    try {
        // Step 1: Look up the channel partner record using the logged-in user's profile ID
        const { data: partnerRecord, error: partnerError } = await supabase
            .from("channel_partners")
            .select("id")
            .eq("user_id", userId)
            .maybeSingle();

        if (partnerError) {
            console.error("Error identifying partner context:", partnerError);
            return { success: false, errorType: "DATABASE_ERROR", message: "Failed to verify partner profile." };
        }

        // Step 2: Grab all access keys generated by this channel partner
        // CRITICAL: We must filter for keys where `from_company` is strictly FALSE.
        // This ensures unlinked keys (which are now from_company = true) do not populate the partner's list.
        let partnerKeyIds: string[] = [];
        if (partnerRecord) {
            const { data: keysData, error: keysError } = await supabase
                .from("access_keys")
                .select("id")
                .eq("channel_partner_id", partnerRecord.id)
                .eq("from_company", false);

            if (keysError) {
                console.error("Error fetching partner keys:", keysError);
                return { success: false, errorType: "DATABASE_ERROR", message: "Failed to retrieve partner keys." };
            }

            if (keysData) {
                partnerKeyIds = keysData.map((k) => k.id).filter(Boolean);
            }
        }

        // Step 3: Query the businesses base table with explicit foreign key names
        let query = supabase
            .from("businesses")
            .select(`
                id,
                owner_id,
                name,
                country,
                region_city,
                access_key_id,
                created_on,
                updated_on,
                manager_profile:user_profiles!owner_id (
                    *,
                    manager_user:users!id (*) 
                ),
                access_key:access_keys!access_key_id (
                    id,
                    key_code,
                    key_type,
                    amount,
                    deduct_trial_fee,
                    expires_at,
                    activated_at,
                    created_on,
                    channel_partner_id,
                    channel_partner:channel_partners!channel_partner_id (
                        id,
                        user_id,
                        valid_from,
                        valid_to,
                        amount,
                        profile:user_profiles!user_id (
                            *,
                            user:users!id (*)
                        )
                    )
                )
            `);


        // Step 4: Run the OR logic cleanly with quoted UUID array signatures
        if (partnerKeyIds.length > 0) {
            const quotedKeyIds = partnerKeyIds.map((id) => `"${id}"`).join(",");
            query = query.or(`owner_id.eq.${userId},access_key_id.in.(${quotedKeyIds})`);
        } else {
            query = query.eq("owner_id", userId);
        }

        const { data, error } = await query;

        if (error) {
            console.error("Database query exception:", error);
            return { success: false, errorType: "DATABASE_ERROR", message: "Failed to retrieve records." };
        }

        // Step 5: Format properties into flat structures matching expectations
        const formattedBusinesses: Business[] = (data || []).map((b: any) => {
            const nestedPartnerArray = b.access_key?.channel_partner;
            const nestedPartner = Array.isArray(nestedPartnerArray)
                ? nestedPartnerArray[0]
                : nestedPartnerArray || null;

            return {
                ...b,
                manager_profile: b.manager_profile || null,
                manager_user: b.manager_profile?.manager_user || null,
                channel_partner: nestedPartner ? {
                    ...nestedPartner,
                    profile: nestedPartner.profile || null,
                    user: nestedPartner.profile?.user || null
                } : null,
            };
        });

        return { success: true, data: formattedBusinesses };

    } catch (e) {
        console.error("Unexpected parsing exception:", e);
        return { success: false, errorType: "DATABASE_ERROR", message: "An unexpected error occurred." };
    }
}


const supabaseAdmin = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export type ProvisionBusinessResponse =
    | { success: true; business: Business; accessKey: AccessKey }
    | { success: false; message: string };

interface ProvisionBusinessPayload {
    // Phase 1 (Wizard Step 1 & 2): Manager Credentials & Profile
    email: string;
    phone: string;
    managerFullName: string;
    managerDob: string;
    managerCountry: string;
    managerCity: string;

    // Phase 1 (Wizard Step 3): Business Specs
    businessName: string;
    businessCountry: string;
    businessCity: string;

    // Phase 2 (Key Form): Target License Configuration
    key_code: string;
    key_type: "TRIAL" | "LIFETIME";
    amount: number;
    deduct_trial_fee: boolean;

    // Self-owned business flag (true = user is creating a business for themselves, false = channel partner creating for another)
    isSelfOwned: boolean;
}

type RawBusinessRow = Omit<Business, 'manager_user' | 'manager_profile' | 'access_key' | 'channel_partners'>;

export async function provisionPendingBusinessAction(payload: ProvisionBusinessPayload): Promise<ProvisionBusinessResponse> {
    const operator = await whichUser.info;
    if (!operator) {
        return { success: false, message: "Unauthorized. Channel partner session required." };
    }

    const calculatedExpiration = payload.key_type === "TRIAL"
        ? new Date(Date.now() + TRIAL_PERIOD_DAYS * 24 * 60 * 60 * 1000).toISOString()
        : null;

    try {
        // Execute the single, unified database transaction
        const { data, error } = await supabaseAdmin.rpc("provision_business_transaction", {
            p_email: payload.isSelfOwned ? operator.email : payload.email,
            p_phone: payload.isSelfOwned ? (operator.phone || "") : payload.phone,
            p_manager_full_name: payload.managerFullName,
            p_manager_dob: payload.managerDob || null,
            p_manager_country: payload.managerCountry,
            p_manager_city: payload.managerCity,
            p_business_name: payload.businessName,
            p_business_country: payload.businessCountry,
            p_business_city: payload.businessCity,
            p_key_code: payload.key_code,
            p_key_type: payload.key_type,
            p_amount: payload.amount,
            p_deduct_trial_fee: payload.deduct_trial_fee,
            p_calculated_expiration: calculatedExpiration,
            p_operator_user_id: operator.id,
            p_is_self_owned: payload.isSelfOwned
        });

        if (error) throw error;
        if (!data || data.success === false) {
            return { success: false, message: data?.message || "Failed to provision business records." };
        }

        const runtimeDate = data.created_on;

        // Construct standard application domain models back to client view layer
        const returnBusiness: Business = {
            id: data.business_id,
            name: payload.businessName,
            country: payload.businessCountry,
            region_city: payload.businessCity,
            owner_id: data.business_user_id,
            access_key_id: data.access_key_id,
            created_on: runtimeDate,
            updated_on: runtimeDate,
            manager_user: {
                id: data.business_user_id,
                email: payload.isSelfOwned ? operator.email : payload.email.trim().toLowerCase(),
                phone: payload.isSelfOwned ? (operator.phone || "") : payload.phone.trim(),
                is_business: true,
                is_individual: false,
                is_active: true,
                email_verified: false,
                phone_verified: false,
                created_on: runtimeDate,
                updated_on: runtimeDate,
                is_deleted: false,
                is_banned: false
            },
            manager_profile: {
                id: data.business_user_id,
                user_id: data.business_user_id,
                full_name: payload.managerFullName,
                date_of_birth: payload.managerDob,
                country: payload.managerCountry,
                region_city: payload.managerCity,
                is_channel_partner: payload.isSelfOwned,
                created_on: runtimeDate,
                updated_on: runtimeDate
            },
            access_key: {
                id: data.access_key_id,
                key_code: payload.key_code,
                key_type: payload.key_type,
                is_active: false,
                activated_at: null,
                expires_at: calculatedExpiration,
                amount: payload.amount,
                deduct_trial_fee: payload.deduct_trial_fee,
                created_on: runtimeDate,
            },
            channel_partner: null
        };

        const returnKey: AccessKey = {
            id: data.access_key_id,
            key_code: payload.key_code,
            key_type: payload.key_type,
            is_active: false,
            activated_at: null,
            expires_at: runtimeDate,
            amount: payload.amount,
            deduct_trial_fee: payload.deduct_trial_fee,
            created_on: runtimeDate,
            business: returnBusiness,
        };

        return { success: true, business: returnBusiness, accessKey: returnKey };

    } catch (err: any) {
        console.error("Critical error inside transactional business orchestration:", err);
        return { success: false, message: err.message || "An unexpected system error occurred." };
    }
}


export async function provisionPendingBusinessActionV2(payload: ProvisionBusinessPayload): Promise<ProvisionBusinessResponse> {

    const operator = await whichUser.info;
    if (!operator) {
        return { success: false, message: "Unauthorized. Channel partner session required." };
    }

    const calculatedExpiration = payload.key_type === "TRIAL"
        ? new Date(Date.now() + TRIAL_PERIOD_DAYS * 24 * 60 * 60 * 1000).toISOString()
        : null;

    try {
        // Execute the single, unified database transaction
        const { data, error } = await supabaseAdmin.rpc("provision_business_transaction_v2", {
            p_email: payload.isSelfOwned ? operator.email : payload.email,
            p_phone: payload.isSelfOwned ? (operator.phone || "") : payload.phone,
            p_manager_full_name: payload.managerFullName,
            p_manager_dob: payload.managerDob || null,
            p_manager_country: payload.managerCountry,
            p_manager_city: payload.managerCity,
            p_business_name: payload.businessName,
            p_business_country: payload.businessCountry,
            p_business_city: payload.businessCity,
            p_key_code: payload.key_code,
            p_key_type: payload.key_type,
            p_amount: payload.amount,
            p_deduct_trial_fee: payload.deduct_trial_fee,
            p_calculated_expiration: calculatedExpiration,
            p_operator_user_id: operator.id,
            p_is_self_owned: payload.isSelfOwned
        });

        if (error) throw error;
        if (!data || data.success === false) {
            return { success: false, message: data?.message || "Failed to provision business records." };
        }

        const runtimeDate = data.created_on;

        // Construct standard application domain models back to client view layer
        const returnBusiness: Business = {
            id: data.business_id,
            name: payload.businessName,
            country: payload.businessCountry,
            region_city: payload.businessCity,
            owner_id: data.business_user_id,
            access_key_id: data.access_key_id,
            created_on: runtimeDate,
            updated_on: runtimeDate,
            manager_user: {
                id: data.business_user_id,
                email: payload.isSelfOwned ? operator.email : payload.email.trim().toLowerCase(),
                phone: payload.isSelfOwned ? (operator.phone || "") : payload.phone.trim(),
                is_business: true,
                is_individual: false,
                is_active: true,
                email_verified: false,
                phone_verified: false,
                created_on: runtimeDate,
                updated_on: runtimeDate,
                is_deleted: false,
                is_banned: false
            },
            manager_profile: {
                id: data.business_user_id,
                user_id: data.business_user_id,
                full_name: payload.managerFullName,
                date_of_birth: payload.managerDob,
                country: payload.managerCountry,
                region_city: payload.managerCity,
                is_channel_partner: payload.isSelfOwned,
                created_on: runtimeDate,
                updated_on: runtimeDate
            },
            access_key: {
                id: data.access_key_id,
                key_code: payload.key_code,
                key_type: payload.key_type,
                is_active: false,
                activated_at: null,
                expires_at: calculatedExpiration,
                amount: payload.amount,
                deduct_trial_fee: payload.deduct_trial_fee,
                created_on: runtimeDate,
            },
            channel_partner: null
        };

        const returnKey: AccessKey = {
            id: data.access_key_id,
            key_code: payload.key_code,
            key_type: payload.key_type,
            is_active: false,
            activated_at: null,
            expires_at: runtimeDate,
            amount: payload.amount,
            deduct_trial_fee: payload.deduct_trial_fee,
            created_on: runtimeDate,
            business: returnBusiness,
        };

        return { success: true, business: returnBusiness, accessKey: returnKey };

    } catch (err: any) {
        console.error("Critical error inside transactional business orchestration:", err);
        return { success: false, message: err.message || "An unexpected system error occurred." };
    }
}

/** Called when the Payment modal fires its callback or webhook verifies completion */
export async function activateAccessKeyAction(keyId: string): Promise<{ success: boolean; message?: string }> {
    const { error } = await supabaseAdmin
        .from("access_keys")
        .update({ is_active: true, activated_at: new Date().toISOString() })
        .eq("id", keyId);

    if (error) return { success: false, message: error.message };
    return { success: true };
}


export interface DeleteResult {
    id: string;
    name: string;
    success: boolean;
    action: "deleted" | "unlinked" | "failed";
    message: string;
}

/**
 * Evaluates deletion/unlinking rules on a single business instance.
 */
export async function deleteOrUnlinkBusinessAction(businessId: string): Promise<DeleteResult> {
    const currentUser = await whichUser.info;
    if (!currentUser) {
        return {
            id: businessId,
            name: "Unknown",
            success: false,
            action: "failed",
            message: "Authentication expired. Please log in again."
        };
    }

    try {
        // Fetch the target business with its access key and channel partner relations
        const { data: business, error: fetchError } = await supabaseAdmin
            .from("businesses")
            .select(`
                id,
                name,
                owner_id,
                access_key:access_keys!access_key_id (
                    id,
                    key_type,
                    created_on,
                    from_company,
                    channel_partner_id,
                    channel_partner:channel_partners!channel_partner_id (
                        user_id
                    )
                )
            `)
            .eq("id", businessId)
            .single();

        if (fetchError || !business) {
            return {
                id: businessId,
                name: "Unknown",
                success: false,
                action: "failed",
                message: "Business record not found in the database."
            };
        }

        const accessKey: any = business.access_key;
        const businessName = business.name;

        if (!accessKey) {
            return {
                id: businessId,
                name: businessName,
                success: false,
                action: "failed",
                message: "This business is not currently tied to an active access key structure."
            };
        }

        const { from_company, channel_partner_id, key_type, created_on } = accessKey;
        const partnerUserId = accessKey.channel_partner?.user_id || null;

        // ── CASE 3: Unlinked Business (channel_partner_id is NOT NULL and from_company is TRUE) ──
        if (channel_partner_id !== null && from_company === true) {
            return {
                id: businessId,
                name: businessName,
                success: false,
                action: "failed",
                message: `"${businessName}" has already been unlinked by its channel partner.`
            };
        }

        // ── CASE 1: Channel Partner Context (from_company is FALSE, channel_partner_id is NOT NULL) ──
        if (from_company === false && channel_partner_id !== null && partnerUserId === currentUser.id) {
            const createdDate = new Date(created_on);

            // 3-month threshold calculation
            const threeMonthsAgo = new Date();
            threeMonthsAgo.setMonth(threeMonthsAgo.getMonth() - 3);

            const fiveMinutesAgo = new Date().setMinutes(new Date().getMinutes() - 5);

            if (key_type === "TRIAL") {
                return {
                    id: businessId,
                    name: businessName,
                    success: false,
                    action: "failed",
                    message: `Trial businesses ("${businessName}") cannot be deleted or unlinked. They expire automatically.`
                };
            }

            if (key_type === "LIFETIME") {
                if (createdDate.getTime() > fiveMinutesAgo) {
                    return {
                        id: businessId,
                        name: businessName,
                        success: false,
                        action: "failed",
                        message: `Lifetime contracts must remain active for at least 3 months before unlinking. "${businessName}" is too new.`
                    };
                } else {
                    // Unlink by setting from_company to true (preserve channel_partner_id)
                    const { error: unlinkError } = await supabaseAdmin
                        .from("access_keys")
                        .update({ from_company: true })
                        .eq("id", accessKey.id);

                    if (unlinkError) throw unlinkError;

                    return {
                        id: businessId,
                        name: businessName,
                        success: true,
                        action: "unlinked",
                        message: `Successfully unlinked "${businessName}" from your partner panel.`
                    };
                }
            }
        }

        // ── CASE 2: Self-Owned Business (channel_partner_id is NULL and from_company is TRUE) ──
        if (channel_partner_id === null && from_company === true) {
            const { error: deleteError } = await supabaseAdmin
                .from("businesses")
                .delete()
                .eq("id", businessId);

            if (deleteError) throw deleteError;

            return {
                id: businessId,
                name: businessName,
                success: true,
                action: "deleted",
                message: `Successfully deleted your self-managed business "${businessName}".`
            };
        }

        // Default Guard
        return {
            id: businessId,
            name: businessName,
            success: false,
            action: "failed",
            message: "You do not have administrative permissions to delete or modify this business."
        };

    } catch (err: any) {
        console.error(`Error processing delete/unlink action for ${businessId}:`, err);
        return {
            id: businessId,
            name: "System Error",
            success: false,
            action: "failed",
            message: err.message || "An unexpected database transaction error occurred."
        };
    }
}

/**
 * Iterates through selected business IDs and runs the deletion/unlinking action on each.
 */
export async function deleteOrUnlinkBusinessesBulkAction(ids: string[]): Promise<DeleteResult[]> {
    const results: DeleteResult[] = [];
    for (const id of ids) {
        const result = await deleteOrUnlinkBusinessAction(id);
        results.push(result);
    }
    return results;
}